Traceback (most recent call last):
  File "c:\users\fatin\appdata\local\programs\python\python39\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\Fatin\AppData\Roaming\Python\Python39\site-packages\nbclient\client.py", line 1117, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\Fatin\AppData\Roaming\Python\Python39\site-packages\nbclient\util.py", line 78, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\Fatin\AppData\Roaming\Python\Python39\site-packages\nbclient\util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "c:\users\fatin\appdata\local\programs\python\python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\Fatin\AppData\Roaming\Python\Python39\site-packages\nbclient\client.py", line 558, in async_execute
    await self.async_execute_cell(
  File "C:\Users\Fatin\AppData\Roaming\Python\Python39\site-packages\nbclient\client.py", line 862, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "C:\Users\Fatin\AppData\Roaming\Python\Python39\site-packages\nbclient\client.py", line 765, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------

# import Sastrawi package
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
import swifter


# create stemmer
factory = StemmerFactory()
stemmer = factory.create_stemmer()

# stemmed
def stemmed_wrapper(term):
    return stemmer.stem(term)

term_dict = {}

for document in data_berita['abstrak']:
    for term in document:
        if term not in term_dict:
            term_dict[term] = ' '
            
print(len(term_dict))
print("------------------------")

for term in term_dict:
    i=0
    if i<10:
        term_dict[term] = stemmed_wrapper(term)
        #print(term,":" ,term_dict[term])
    
print(term_dict)
print("------------------------")


# apply stemmed term to dataframe
def get_stemmed_term(document):
    return [term_dict[term] for term in document]

data_berita['abstrak'] = data_berita['abstrak'].swifter.apply(get_stemmed_term)
print(data_berita['abstrak'])
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mTypeError[0m                                 Traceback (most recent call last)
[1;32mc:\users\fatin\appdata\local\programs\python\python39\lib\site-packages\swifter\swifter.py[0m in [0;36mapply[1;34m(self, func, convert_dtype, args, **kwds)[0m
[0;32m    238[0m             [1;32mwith[0m [0msuppress_stdout_stderr_logging[0m[1;33m([0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 239[1;33m                 [0mtmp_df[0m [1;33m=[0m [0mfunc[0m[1;33m([0m[0msample[0m[1;33m,[0m [1;33m*[0m[0margs[0m[1;33m,[0m [1;33m**[0m[0mkwds[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    240[0m                 [0msample_df[0m [1;33m=[0m [0msample[0m[1;33m.[0m[0mapply[0m[1;33m([0m[0mfunc[0m[1;33m,[0m [0mconvert_dtype[0m[1;33m=[0m[0mconvert_dtype[0m[1;33m,[0m [0margs[0m[1;33m=[0m[0margs[0m[1;33m,[0m [1;33m**[0m[0mkwds[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\AppData\Local\Temp/ipykernel_15876/141925463.py[0m in [0;36mget_stemmed_term[1;34m(document)[0m
[0;32m     35[0m [1;32mdef[0m [0mget_stemmed_term[0m[1;33m([0m[0mdocument[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m---> 36[1;33m     [1;32mreturn[0m [1;33m[[0m[0mterm_dict[0m[1;33m[[0m[0mterm[0m[1;33m][0m [1;32mfor[0m [0mterm[0m [1;32min[0m [0mdocument[0m[1;33m][0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     37[0m [1;33m[0m[0m

[1;32m~\AppData\Local\Temp/ipykernel_15876/141925463.py[0m in [0;36m<listcomp>[1;34m(.0)[0m
[0;32m     35[0m [1;32mdef[0m [0mget_stemmed_term[0m[1;33m([0m[0mdocument[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m---> 36[1;33m     [1;32mreturn[0m [1;33m[[0m[0mterm_dict[0m[1;33m[[0m[0mterm[0m[1;33m][0m [1;32mfor[0m [0mterm[0m [1;32min[0m [0mdocument[0m[1;33m][0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     37[0m [1;33m[0m[0m

[1;31mTypeError[0m: unhashable type: 'list'

During handling of the above exception, another exception occurred:

[1;31mAttributeError[0m                            Traceback (most recent call last)
[1;32m~\AppData\Local\Temp/ipykernel_15876/141925463.py[0m in [0;36m<module>[1;34m[0m
[0;32m     36[0m     [1;32mreturn[0m [1;33m[[0m[0mterm_dict[0m[1;33m[[0m[0mterm[0m[1;33m][0m [1;32mfor[0m [0mterm[0m [1;32min[0m [0mdocument[0m[1;33m][0m[1;33m[0m[1;33m[0m[0m
[0;32m     37[0m [1;33m[0m[0m
[1;32m---> 38[1;33m [0mdata_berita[0m[1;33m[[0m[1;34m'abstrak'[0m[1;33m][0m [1;33m=[0m [0mdata_berita[0m[1;33m[[0m[1;34m'abstrak'[0m[1;33m][0m[1;33m.[0m[0mswifter[0m[1;33m.[0m[0mapply[0m[1;33m([0m[0mget_stemmed_term[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     39[0m [0mprint[0m[1;33m([0m[0mdata_berita[0m[1;33m[[0m[1;34m'abstrak'[0m[1;33m][0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;32mc:\users\fatin\appdata\local\programs\python\python39\lib\site-packages\swifter\swifter.py[0m in [0;36mapply[1;34m(self, func, convert_dtype, args, **kwds)[0m
[0;32m    257[0m                 [1;32mif[0m [0mself[0m[1;33m.[0m[0m_progress_bar[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m    258[0m                     [0mtqdm[0m[1;33m.[0m[0mpandas[0m[1;33m([0m[0mdesc[0m[1;33m=[0m[0mself[0m[1;33m.[0m[0m_progress_bar_desc[0m [1;32mor[0m [1;34m"Pandas Apply"[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 259[1;33m                     [1;32mreturn[0m [0mself[0m[1;33m.[0m[0m_obj[0m[1;33m.[0m[0mprogress_apply[0m[1;33m([0m[0mfunc[0m[1;33m,[0m [0mconvert_dtype[0m[1;33m=[0m[0mconvert_dtype[0m[1;33m,[0m [0margs[0m[1;33m=[0m[0margs[0m[1;33m,[0m [1;33m**[0m[0mkwds[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    260[0m                 [1;32melse[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m    261[0m                     [1;32mreturn[0m [0mself[0m[1;33m.[0m[0m_obj[0m[1;33m.[0m[0mapply[0m[1;33m([0m[0mfunc[0m[1;33m,[0m [0mconvert_dtype[0m[1;33m=[0m[0mconvert_dtype[0m[1;33m,[0m [0margs[0m[1;33m=[0m[0margs[0m[1;33m,[0m [1;33m**[0m[0mkwds[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;32mc:\users\fatin\appdata\local\programs\python\python39\lib\site-packages\tqdm\std.py[0m in [0;36minner[1;34m(df, func, *args, **kwargs)[0m
[0;32m    792[0m [1;33m[0m[0m
[0;32m    793[0m                 [1;32mtry[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 794[1;33m                     [0mfunc[0m [1;33m=[0m [0mdf[0m[1;33m.[0m[0m_is_builtin_func[0m[1;33m([0m[0mfunc[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    795[0m                 [1;32mexcept[0m [0mTypeError[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m    796[0m                     [1;32mpass[0m[1;33m[0m[1;33m[0m[0m

[1;32mc:\users\fatin\appdata\local\programs\python\python39\lib\site-packages\pandas\core\generic.py[0m in [0;36m__getattr__[1;34m(self, name)[0m
[0;32m   5573[0m         ):
[0;32m   5574[0m             [1;32mreturn[0m [0mself[0m[1;33m[[0m[0mname[0m[1;33m][0m[1;33m[0m[1;33m[0m[0m
[1;32m-> 5575[1;33m         [1;32mreturn[0m [0mobject[0m[1;33m.[0m[0m__getattribute__[0m[1;33m([0m[0mself[0m[1;33m,[0m [0mname[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m   5576[0m [1;33m[0m[0m
[0;32m   5577[0m     [1;32mdef[0m [0m__setattr__[0m[1;33m([0m[0mself[0m[1;33m,[0m [0mname[0m[1;33m:[0m [0mstr[0m[1;33m,[0m [0mvalue[0m[1;33m)[0m [1;33m->[0m [1;32mNone[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;31mAttributeError[0m: 'Series' object has no attribute '_is_builtin_func'
AttributeError: 'Series' object has no attribute '_is_builtin_func'

